### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by denniseffing** [i-am-tom/i-am-tom.github.io#7]
Hi @i-am-tom,

I am a big fan of your fantasy land blog series. I wanted to recommend your series to a few colleagues of mine today but apparently, your website is down 😞 I would really appreciate it if you could restore it!

**Comment by tgrecojs** [comment]
Beat me to the punch here @denniseffing! And it wasn't even close 🙂. While this issue gets worked out, you can still access the content (or direct your colleagues to it) via archive.org. 

@denniseffing here's a link to the series' homepage - [tomharding.me/fantasy-land](https://web.archive.org/web/20231206131039/http://www.tomharding.me/fantasy-land/).

I have a deep appreciation for that series as well, so thank you for putting that treasure trove of a series out there @i-am-tom! ❤️  

I'm not quite sure what "ceritificate transparency" refers to but that shows when you hover over the last change on [archive.org's summary page for the website](https://web.archive.org/web/20240701000000*/tomharding.com).


![ss_06162024_000382](https://github.com/i-am-tom/i-am-tom.github.io/assets/6646552/1c4c920a-a65a-4912-9eb4-68f4db1b5890)


Thanks again for all the great work!

**Comment by baweaver** [comment]
Unfortunately it appears the main domain name has been taken over by a scammer.

**Comment by tgrecojs** [comment]
good catch @baweaver! 

i'm seeing that the CNAME record has been deleted, so all who wish to visit tomharding.me should instead visit [i-am-tom.github.io](https://github.com/i-am-tom/i-am-tom.github.io)

cc @denniseffing

**Comment by i-am-tom** [comment]
Hey all,

Firstly, thanks for your lovely comments :) Yeah, it's really annoying to have it stolen - I guess I missed the renewal deadline 😳 As @tgrecojs mentions, it's still available at i-am-tom.github.io, so hopefully people should still be able to find them. 🤞

**Comment by denniseffing** [comment]
@i-am-tom I think your domain tomharding.me is available for registration again. Thought you’d want to know in case you’re interested in getting it back. 🙂
