### ISSUE TITLE
Can't find the blogposts about FP anymore

### ISSUE THREAD

**Issue by tajakobsen** [i-am-tom/i-am-tom.github.io#9]
Hi @i-am-tom , this is another Tom!

I was trying to go to this bookmark: https://www.tomharding.me/2017/03/03/fantas-eel-and-specification/ but instead I just got some gambling spam. Is it possible that your site has been hacked?

**Comment by i-am-tom** [comment]
Hey! Unfortunately, the domain name was registered with an old email address and so I missed the expiry date. This post still exists here: https://i-am-tom.github.io/2017/03/03/fantas-eel-and-specification/
